//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// Este código fuente fue generado automáticamente por wsdl, Versión=4.6.1055.0.
// 
namespace AggityPresenceControlWSAsmxClient
{
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "PunchDataServiceSoap", Namespace = "http://tempuri.org/")]
    public partial class PunchDataServiceWSProxy : System.Web.Services.Protocols.SoapHttpClientProtocol {

        private System.Threading.SendOrPostCallback SendPunchDataOperationCompleted;

        /// <remarks/>
        public PunchDataServiceWSProxy() {
            this.Url = "http://localhost/AggityPresenceControlWS_ASMX/PunchDataService.asmx";
        }

        /// <remarks/>
        public event SendPunchDataCompletedEventHandler SendPunchDataCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SendPunchData", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SendPunchData(string punchDataBaseJson) {
            object[] results = this.Invoke("SendPunchData", new object[] {
                    punchDataBaseJson});
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginSendPunchData(string punchDataBaseJson, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("SendPunchData", new object[] {
                    punchDataBaseJson}, callback, asyncState);
        }

        /// <remarks/>
        public bool EndSendPunchData(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((bool)(results[0]));
        }

        /// <remarks/>
        public void SendPunchDataAsync(string punchDataBaseJson) {
            this.SendPunchDataAsync(punchDataBaseJson, null);
        }

        /// <remarks/>
        public void SendPunchDataAsync(string punchDataBaseJson, object userState) {
            if ((this.SendPunchDataOperationCompleted == null)) {
                this.SendPunchDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSendPunchDataOperationCompleted);
            }
            this.InvokeAsync("SendPunchData", new object[] {
                    punchDataBaseJson}, this.SendPunchDataOperationCompleted, userState);
        }

        private void OnSendPunchDataOperationCompleted(object arg) {
            if ((this.SendPunchDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SendPunchDataCompleted(this, new SendPunchDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    public delegate void SendPunchDataCompletedEventHandler(object sender, SendPunchDataCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SendPunchDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

        private object[] results;

        internal SendPunchDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState) {
            this.results = results;
        }

        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}